# Generated by Django 5.2.1 on 2025-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
